/*
 * port_config.h
 *
 * Created: 3/31/2022 11:42:37 PM
 *  Author: fawzy
 */ 


#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_


#include "memory_map.h"
#include "port_initial.h"

#define  port_conc(b7,b6,b5,b4,b3,b2,b1,b0)             port_help(b7,b6,b5,b4,b3,b2,b1,b0)
#define  port_help(b7,b6,b5,b4,b3,b2,b1,b0)             0b##b7##b6##b5##b4##b3##b2##b1##b0

#define   DDRA_DIRECTION          port_conc(PORTA_PIN7_DIR,PORTA_PIN6_DIR ,PORTA_PIN5_DIR ,PORTA_PIN4_DIR ,PORTA_PIN3_DIR ,PORTA_PIN2_DIR ,PORTA_PIN1_DIR ,PORTA_PIN0_DIR )   
#define   DDRB_DIRECTION          port_conc(PORTB_PIN7_DIR,PORTB_PIN6_DIR ,PORTB_PIN5_DIR ,PORTB_PIN4_DIR ,PORTB_PIN3_DIR ,PORTB_PIN2_DIR ,PORTB_PIN1_DIR ,PORTB_PIN0_DIR )
#define   DDRC_DIRECTION          port_conc(PORTC_PIN7_DIR,PORTC_PIN6_DIR ,PORTC_PIN5_DIR ,PORTC_PIN4_DIR ,PORTC_PIN3_DIR ,PORTC_PIN2_DIR ,PORTC_PIN1_DIR ,PORTC_PIN1_DIR )
#define   DDRD_DIRECTION          port_conc(PORTD_PIN7_DIR,PORTD_PIN6_DIR ,PORTD_PIN5_DIR ,PORTD_PIN4_DIR ,PORTD_PIN3_DIR ,PORTD_PIN2_DIR ,PORTD_PIN1_DIR ,PORTD_PIN0_DIR )


#define   PORTA_VALUE         port_conc(PORTA_PIN7_VALUE ,PORTA_PIN6_VALUE ,PORTA_PIN5_VALUE ,PORTA_PIN4_VALUE ,PORTA_PIN3_VALUE ,PORTA_PIN2_VALUE ,PORTA_PIN1_VALUE ,PORTA_PIN0_VALUE)
#define   PORTB_VALUE         port_conc(PORTB_PIN7_VALUE ,PORTB_PIN6_VALUE ,PORTB_PIN5_VALUE ,PORTB_PIN4_VALUE ,PORTB_PIN3_VALUE ,PORTB_PIN2_VALUE ,PORTB_PIN1_VALUE ,PORTB_PIN0_VALUE)
#define   PORTC_VALUE         port_conc(PORTC_PIN7_VALUE ,PORTC_PIN6_VALUE ,PORTC_PIN5_VALUE ,PORTC_PIN4_VALUE ,PORTC_PIN3_VALUE ,PORTC_PIN2_VALUE ,PORTC_PIN1_VALUE ,PORTC_PIN0_VALUE)
#define   PORTD_VALUE         port_conc(PORTD_PIN7_VALUE ,PORTD_PIN6_VALUE ,PORTD_PIN5_VALUE ,PORTD_PIN4_VALUE ,PORTD_PIN3_VALUE ,PORTD_PIN2_VALUE ,PORTD_PIN1_VALUE ,PORTD_PIN0_VALUE)


void direction_and_port_init(void);  





#endif /* PORT_CONFIG_H_ */